export enum USER_ACCOUNT_TYPE_LABELS {
  TENANT = 'Tenant',
  HOME_OWNER = 'Home Owner',
}

export enum SEARCH_STATUS_LABELS {
  NOT_LOOKING = 'Not Looking',
  PASSIVE = 'Passive',
  ACTIVE = 'Active',
}

export enum LEASE_TYPES {
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export enum USER_ACCOUNT_TYPES {
  TENANT = 'TENANT',
  HOME_OWNER = 'HOME_OWNER',
}

export enum SEARCH_STATUS {
  NOT_LOOKING = 'NOT_LOOKING',
  PASSIVE = 'PASSIVE',
  ACTIVE = 'ACTIVE',
}

export enum NOTIFICATION_TYPE {
  NEW_HOME_LISTING = 'NEW_HOME_LISTING'
}

export enum NOTIFICATION_TARGET_TYPE {
  USER = 'USER',
}

export enum SUBSCRIPTION_TYPE {
  USER_LOCATION_PREFERENCES_UPDATED = 'USER_LOCATION_PREFERENCES_UPDATED'
}
