export enum LEASE_TYPES {
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export enum USER_ACCOUNT_TYPES {
  TENANT = 'TENANT',
  HOME_OWNER = 'HOME_OWNER',
}

export enum USER_ACCOUNT_TYPE_LABELS {
  TENANT = 'Tenant',
  HOME_OWNER = 'Home Owner',
}

export enum NOTIFICATION_TYPE {
  NEW_HOME_LISTING = 'NEW_HOME_LISTING'
}

export enum NOTIFICATION_TARGET_TYPE {
  USER = 'USER',
}

export enum SUBSCRIPTION_TYPE {
  USER_LOCATION_PREFERENCES_UPDATED = 'USER_LOCATION_PREFERENCES_UPDATED'
}
