export enum USER_ACCOUNT_TYPE_LABELS {
  TENANT = 'Tenant',
  HOME_OWNER = 'Home Owner',
}

export enum SEARCH_STATUS_LABELS {
  NOT_LOOKING = 'Not Looking',
  PASSIVE = 'Passive',
  ACTIVE = 'Active',
}

export enum HOME_TYPE_LABELS {
  ANY = 'Any',
  ROOM = 'Room',
  BASEMENT_FLOOR = 'Basement Floor',
  STUDIO = 'Studio',
  CONDO = 'Condo',
  APARTMENT = 'Apartment',
  TOWN_HOME = 'Town Home',
  HOUSE = 'House',
}

/** */

export enum LEASE_TYPES {
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export enum USER_ACCOUNT_TYPES {
  TENANT = 'TENANT',
  HOME_OWNER = 'HOME_OWNER',
}

export enum HOME_TYPES {
  ANY = 'ANY',
  ROOM = 'ROOM',
  BASEMENT_FLOOR = 'BASEMENT_FLOOR',
  STUDIO = 'STUDIO',
  CONDO = 'CONDO',
  APARTMENT = 'APARTMENT',
  TOWN_HOME = 'TOWN_HOME',
  HOUSE = 'HOUSE',
}

export enum SEARCH_STATUS {
  NOT_LOOKING = 'NOT_LOOKING',
  PASSIVE = 'PASSIVE',
  ACTIVE = 'ACTIVE',
}

export enum NOTIFICATION_TYPE {
  NEW_HOME_LISTING = 'NEW_HOME_LISTING',
  HOME_LISTING_REQUEST_ACCEPTED = 'HOME_LISTING_REQUEST_ACCEPTED',
  HOME_LISTING_REQUEST_DECLINED = 'HOME_LISTING_REQUEST_DECLINED',
  HOME_LISTING_REQUEST_SENT = 'HOME_LISTING_REQUEST_SENT',
  HOME_LISTING_REQUEST_CANCELED = 'HOME_LISTING_REQUEST_CANCELED',
}

export enum NOTIFICATION_TARGET_TYPE {
  USER = 'USER',
  HOME_LISTING = 'HOME_LISTING',
  HOME_LISTING_REQUEST = 'HOME_LISTING_REQUEST',
}

export enum SUBSCRIPTION_TYPE {
  USER_LOCATION_PREFERENCES_UPDATED = 'USER_LOCATION_PREFERENCES_UPDATED'
}

export enum EVENT_TYPES {
  HOME_LISTING_UPDATED = 'HOME_LISTING_UPDATED',
  HOME_LISTING_DELETED = 'HOME_LISTING_DELETED',
  HOME_LISTING_REQUEST_ACCEPTED = 'HOME_LISTING_REQUEST_ACCEPTED',
  HOME_LISTING_REQUEST_DECLINED = 'HOME_LISTING_REQUEST_DECLINED',
  HOME_LISTING_REQUEST_SENT = 'HOME_LISTING_REQUEST_SENT',
  HOME_LISTING_REQUEST_CANCELED = 'HOME_LISTING_REQUEST_CANCELED',
}